import Link from "next/link";
import {
  LegalHero,
  LegalBody,
  LegalSection,
  LegalParagraph,
  LegalList,
  legalLinkClass,
} from "@/components/legal/LegalDocument";

export const metadata = {
  title: "Privacy Policy | Joti Foundation",
  description:
    "How Joti Foundation collects, uses, and discloses personal data when you use our website.",
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <LegalHero
        title="Privacy Policy"
        effectiveDate="January 26, 2021"
        intro="Joti Foundation (“us”, “we”, or “our”) operates jotifoundation.org (the “Service”). We put great effort into making sure that we secure your personally identifiable information and use it properly."
      />

      <LegalBody>
        <LegalParagraph>
          This page informs you of our policies regarding the collection,
          use, and disclosure of personal data when you use our Service and
          the choices you have associated with that data.
        </LegalParagraph>
        <LegalParagraph>
          We use your data to provide and improve our Service. By using our
          Service, you agree to the collection and use of information in
          accordance with this policy. Unless otherwise defined in this
          Privacy Policy, terms used in this Privacy Policy have the same
          meanings as in our{" "}
          <Link href="/terms-of-service" className={legalLinkClass}>
            Terms of Service
          </Link>
          .
        </LegalParagraph>
        <LegalParagraph>
          By continuing to use the Service, you accept the latest version of
          our Terms of Service. You should refresh your browser each time
          you visit the website to ensure that you download the most
          up-to-date version of the website, including the latest version of
          the Terms of Service and this Privacy Policy.
        </LegalParagraph>

        <LegalSection heading="Definitions">
          <LegalList>
            <li>
              <strong className="text-on-background">Personal Data</strong>{" "}
              relates to information about a living individual who can be
              identified from that data (or from those and other
              information either in our possession or likely to come into
              our possession).
            </li>
            <li>
              <strong className="text-on-background">Usage Data</strong> is
              data that is collected automatically, either generated by the
              use of the Service or from the Service infrastructure itself
              (for example, the duration of a page visit).
            </li>
            <li>
              <strong className="text-on-background">Cookies</strong> are
              small pieces of data, sent from our Service and stored on the
              user&rsquo;s web browser, which is used specifically for
              enhancing usability of our Service.
            </li>
            <li>
              A{" "}
              <strong className="text-on-background">Data Controller</strong>{" "}
              is a person who (either alone or jointly or in common with
              other persons) determines the purposes for which and the
              manner in which any personal data are, or are to be,
              processed. For the purpose of this Privacy Policy, we are a
              Data Controller of your data.
            </li>
            <li>
              A{" "}
              <strong className="text-on-background">
                Data Processor (or Service Provider)
              </strong>{" "}
              means any person (other than an employee of the Data
              Controller) who processes the data on behalf of the Data
              Controller. We may use the services of various Service
              Providers in order to process your data more effectively.
            </li>
            <li>
              A <strong className="text-on-background">Data Subject</strong>{" "}
              is any living individual who is the subject of Personal Data.
            </li>
            <li>
              The <strong className="text-on-background">User</strong> is
              the individual using our Service. The User corresponds to the
              Data Subject, who is the subject of the Personal Data.
            </li>
          </LegalList>
        </LegalSection>

        <LegalSection heading="Information Collection and Use">
          <LegalParagraph>
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </LegalParagraph>
          <LegalParagraph>
            <strong className="text-on-background">Personal Data.</strong>{" "}
            While using our Service, we may ask you to provide us with
            certain personally identifiable information that can be used to
            contact or identify you (&ldquo;Personal Data&rdquo;).
            Personally identifiable information may include, but is not
            limited to:
          </LegalParagraph>
          <LegalList>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Cookies and Usage Data</li>
          </LegalList>
          <LegalParagraph>
            We may use your Personal Data to contact you with newsletters,
            marketing or promotional materials and other information that
            may be of interest to you. You may opt out of receiving any, or
            all, of these communications from us by following the
            unsubscribe link or instructions provided in any email we send.
          </LegalParagraph>
          <LegalParagraph>
            <strong className="text-on-background">Usage Data.</strong> We
            may also collect information on how the Service is accessed and
            used (&ldquo;Usage Data&rdquo;). This Usage Data may include
            information such as your computer&rsquo;s Internet Protocol
            address (e.g. IP address), browser type, browser version, the
            pages of our Service that you visit, the time and date of your
            visit, the time spent on those pages, unique device identifiers
            and other diagnostic data.
          </LegalParagraph>
          <LegalParagraph>
            <strong className="text-on-background">
              Tracking &amp; Cookie Data.
            </strong>{" "}
            We use cookies and similar tracking technologies to track the
            activity on our Service and hold certain information. Cookies
            are files with a small amount of data, which may include an
            anonymous unique identifier. Cookies are sent to your browser
            from our website and stored on your device. Tracking
            technologies also used are beacons, tags, and scripts to collect
            and track information and to improve and analyze our Service.
          </LegalParagraph>
          <LegalParagraph>
            You can instruct your browser to refuse all cookies or to
            indicate when a cookie is being sent. However, if you do not
            accept cookies, you may not be able to use some portions of our
            Service. Examples of cookies we use:
          </LegalParagraph>
          <LegalList>
            <li>
              <strong className="text-on-background">
                Session Cookies.
              </strong>{" "}
              We use Session Cookies to operate our Service. Your device
              removes session cookies when you close your browser.
            </li>
            <li>
              <strong className="text-on-background">
                Preference Cookies.
              </strong>{" "}
              We use Preference Cookies to remember your preferences and
              various settings.
            </li>
            <li>
              <strong className="text-on-background">
                Security Cookies.
              </strong>{" "}
              We use Security Cookies for security purposes.
            </li>
          </LegalList>
        </LegalSection>

        <LegalSection heading="Use of Data">
          <LegalParagraph>
            Joti Foundation uses the collected data for various purposes:
          </LegalParagraph>
          <LegalList>
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>
              To allow you to participate in interactive features of our
              Service when you choose to do so
            </li>
            <li>To provide customer support</li>
            <li>
              To gather analysis or valuable information so that we can
              improve our Service
            </li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            <li>
              To provide you with news, special offers and general
              information about other goods, services and events which we
              offer that are similar to those that you have already
              purchased or enquired about, unless you have opted not to
              receive such information
            </li>
          </LegalList>
          <LegalParagraph>
            We commit to process personally identifiable information for the
            purposes described in this policy.
          </LegalParagraph>
        </LegalSection>

        <LegalSection heading="Retention of Data">
          <LegalParagraph>
            Joti Foundation will retain your Personal Data only for as long
            as is necessary for the purposes set out in this Privacy Policy.
            We will retain and use your Personal Data to the extent
            necessary to comply with our legal obligations (for example, if
            we are required to retain your data to comply with applicable
            laws), resolve disputes, and enforce our legal agreements and
            policies.
          </LegalParagraph>
          <LegalParagraph>
            Joti Foundation will also retain Usage Data for the purpose of
            internal analysis. Usage Data is generally retained for a
            shorter period of time, except when this data is used to
            strengthen the security or to improve the functionality of our
            Service, or we are legally obligated to retain this data for
            longer time periods.
          </LegalParagraph>
        </LegalSection>

        <LegalSection heading="Transfer of Data">
          <LegalParagraph>
            Your information, including Personal Data, may be transferred to
            and maintained on computers located outside of your state,
            province, country or other governmental jurisdiction where the
            data protection laws may differ than those from your
            jurisdiction.
          </LegalParagraph>
          <LegalParagraph>
            If you are located outside India and choose to provide
            information to us, please note that we transfer the data,
            including Personal Data, to India and process it there.
          </LegalParagraph>
          <LegalParagraph>
            Your consent to this Privacy Policy followed by your submission
            of such information represents your agreement to that transfer.
          </LegalParagraph>
          <LegalParagraph>
            Joti Foundation will take all steps reasonably necessary to
            ensure that your data is treated securely and in accordance with
            this Privacy Policy and no transfer of your Personal Data will
            take place to an organization or a country unless there are
            adequate controls in place including the security of your data
            and other personal information.
          </LegalParagraph>
        </LegalSection>

        <LegalSection heading="Disclosure of Data">
          <LegalParagraph>
            <strong className="text-on-background">
              Disclosure for Law Enforcement.
            </strong>{" "}
            Under certain circumstances, Joti Foundation may be required to
            disclose your Personal Data if required to do so by law or in
            response to valid requests by public authorities (e.g. a court
            or a government agency).
          </LegalParagraph>
          <LegalParagraph>
            <strong className="text-on-background">
              Legal Requirements.
            </strong>{" "}
            Joti Foundation may disclose your Personal Data in the good
            faith belief that such action is necessary to:
          </LegalParagraph>
          <LegalList>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of Joti Foundation</li>
            <li>
              Prevent or investigate possible wrongdoing in connection with
              the Service
            </li>
            <li>
              Protect the personal safety of users of the Service or the
              public
            </li>
            <li>Protect against legal liability</li>
          </LegalList>
        </LegalSection>

        <LegalSection heading="Security of Data">
          <LegalParagraph>
            The security of your data is important to us but remember that
            no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While we strive to use
            commercially acceptable means to protect your Personal Data, we
            cannot guarantee its absolute security.
          </LegalParagraph>
        </LegalSection>

        <LegalSection heading="Your Rights">
          <LegalParagraph>
            Joti Foundation aims to take reasonable steps to allow you to
            correct, amend, delete, or limit the use of your Personal Data.
          </LegalParagraph>
          <LegalParagraph>
            Whenever made possible, you can update your Personal Data
            directly within your account settings section. If you are
            unable to change your Personal Data, please contact us to make
            the required changes.
          </LegalParagraph>
          <LegalParagraph>
            If you wish to be informed what Personal Data we hold about you
            and if you want it to be removed from our systems, please
            contact us.
          </LegalParagraph>
          <LegalParagraph>In certain circumstances, you have the right:</LegalParagraph>
          <LegalList>
            <li>
              To access and receive a copy of the Personal Data we hold
              about you
            </li>
            <li>To rectify any Personal Data held about you that is inaccurate</li>
            <li>To request the deletion of Personal Data held about you</li>
          </LegalList>
          <LegalParagraph>
            You have the right to move the information you provide to Joti
            Foundation in accordance with your right to data portability.
            You can request to obtain a copy of your Personal Data in a
            commonly used electronic format so that you can manage and move
            it. Please note that we may ask you to verify your identity
            before responding to such requests.
          </LegalParagraph>
        </LegalSection>

        <LegalSection heading="Service Providers">
          <LegalParagraph>
            We may employ third party companies and individuals to
            facilitate our Service (&ldquo;Service Providers&rdquo;), to
            provide the Service on our behalf, to perform Service-related
            services or to assist us in analysing how our Service is used.
          </LegalParagraph>
          <LegalParagraph>
            These third parties have access to your Personal Data only to
            perform these tasks on our behalf and are obligated not to
            disclose or use it for any other purpose. We do not sell, rent
            or lease your personally identifiable information.
          </LegalParagraph>
        </LegalSection>

        <LegalSection heading="Analytics">
          <LegalParagraph>
            We may use third-party Service Providers and standard analytics
            tools to monitor and analyze the use of our Service. The privacy
            practices of these tools are subject to their own privacy
            policies and they use their own cookies to provide their
            Service.
          </LegalParagraph>
          <LegalParagraph>
            <strong className="text-on-background">
              Google Analytics.
            </strong>{" "}
            Google Analytics is a web analytics Service offered by Google
            that tracks and reports website traffic. Google uses the data
            collected to track and monitor the use of our Service. This data
            is shared with other Google services. Google may use the
            collected data to contextualize and personalize the ads of its
            own advertising network.
          </LegalParagraph>
          <LegalParagraph>
            You can opt out of having your activity on the Joti Foundation
            website made available to Google Analytics by installing the
            Google Analytics opt-out browser add-on. For more information on
            the privacy practices of Google, please visit the{" "}
            <a
              href="http://www.google.com/intl/en/policies/privacy/"
              target="_blank"
              rel="noopener noreferrer"
              className={legalLinkClass}
            >
              Google Privacy &amp; Terms
            </a>{" "}
            web page.
          </LegalParagraph>
        </LegalSection>

        <LegalSection heading="Links to Other Sites">
          <LegalParagraph>
            The Joti Foundation website may contain links to other sites
            that are not operated by us. If you click on a third-party link,
            you will be directed to that third-party&rsquo;s site. We
            strongly advise you to review the Privacy Policy of every site
            you visit.
          </LegalParagraph>
          <LegalParagraph>
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third-party sites
            or services.
          </LegalParagraph>
        </LegalSection>

        <LegalSection heading="Children’s Privacy">
          <LegalParagraph>
            Our Service does not address anyone under the age of 13
            (&ldquo;Children&rdquo;).
          </LegalParagraph>
          <LegalParagraph>
            We do not knowingly collect personally identifiable information
            from anyone under the age of 13. If you are a parent or guardian
            and you are aware that your child has provided us with Personal
            Data, please contact us. If we become aware that we have
            collected Personal Data from your child without verification of
            parental consent, we take steps to remove that information from
            our servers.
          </LegalParagraph>
        </LegalSection>

        <LegalSection heading="Your EU Data Subject Rights">
          <LegalParagraph>
            If EU data protection laws apply to the processing of your
            personal data by Joti Foundation, then the following terms
            apply.
          </LegalParagraph>
          <LegalParagraph>
            Where we process your Personal Data as a Data Controller, the
            processing is based on the following lawful grounds:
          </LegalParagraph>
          <LegalList>
            <li>
              All processing of your personal data which is not based on the
              lawful grounds indicated below is based on your consent.
            </li>
            <li>
              We will process your personal data to comply with a legal
              obligation and to protect your and others&rsquo; vital
              interests.
            </li>
            <li>
              We will further rely on our legitimate interests, which we
              believe are not overridden by your fundamental rights and
              freedoms, for the following purposes: communications with you,
              including direct marketing where you are our client or a user
              of our client, or where you make contact with us through the
              Joti Foundation website and other digital assets; cyber
              security; support, customer relations, Service operations;
              enhancements and improvements to yours and other
              users&rsquo; experience with our Service; and fraud detection
              and misuse of the Service.
            </li>
          </LegalList>
          <LegalParagraph>
            In addition to your rights under other sections in this policy,
            you have the following rights:
          </LegalParagraph>
          <LegalList>
            <li>
              At any time, contact us if you want to withdraw your consent
              to the processing of your personal data. Exercising this
              right will not affect the lawfulness of processing based on
              consent before its withdrawal.
            </li>
            <li>
              Request to delete or restrict access to your personal data. We
              will review your request and use our judgment, pursuant to
              the provisions of the applicable law, to reach a decision
              about your request.
            </li>
            <li>
              If you exercise one (or more) of the above-mentioned rights,
              in accordance with the provisions of applicable law, you may
              request to be informed that third parties that hold your
              personal data, in accordance with this policy, will act
              accordingly.
            </li>
            <li>
              You may object to the processing of your personal data for
              direct marketing purposes.
            </li>
            <li>
              You have the right not to be subject to a decision based
              solely on automated processing, including profiling, which
              produces legal effects concerning you or similarly
              significantly affecting you.
            </li>
            <li>
              You have a right to lodge a complaint with a data protection
              supervisory authority of your habitual residence, place of
              work or of an alleged infringement of the GDPR.
            </li>
          </LegalList>
          <LegalParagraph>
            A summary and further details about your rights under EU data
            protection laws is available on the{" "}
            <a
              href="https://ec.europa.eu/info/law/law-topic/data-protection/reform/rights-citizens_en"
              target="_blank"
              rel="noopener noreferrer"
              className={legalLinkClass}
            >
              EU Commission&rsquo;s website
            </a>
            .
          </LegalParagraph>
          <LegalParagraph>
            If we need to delete your personal data following your request,
            it will take some time until we completely delete residual
            copies of your personal data from our active servers and from
            our backup systems.
          </LegalParagraph>
          <LegalParagraph>
            If you have any concerns about the way we process your personal
            data, you are welcome to contact our privacy team at Joti
            Foundation. We will look into your inquiry and make good-faith
            efforts to respond promptly.
          </LegalParagraph>
        </LegalSection>

        <LegalSection heading="Changes to This Privacy Policy">
          <LegalParagraph>
            We may update our Privacy Policy from time to time. We will
            notify you of any changes by posting the new Privacy Policy on
            this page.
          </LegalParagraph>
          <LegalParagraph>
            We will let you know via email and/or a prominent notice on our
            website, prior to the change becoming effective and update the
            &ldquo;effective date&rdquo; at the top of this Privacy Policy.
          </LegalParagraph>
          <LegalParagraph>
            You are advised to review this Privacy Policy periodically for
            any changes. Changes to this Privacy Policy are effective when
            they are posted on this page.
          </LegalParagraph>
        </LegalSection>

        <LegalSection heading="Contact Us">
          <LegalParagraph>
            If you have any questions about this Privacy Policy, please
            contact us at{" "}
            <a href="mailto:info@jotifoundation.org" className={legalLinkClass}>
              info@jotifoundation.org
            </a>
            .
          </LegalParagraph>
        </LegalSection>
      </LegalBody>
    </>
  );
}
